//! The port abstraction: [`PortValue`], [`PortId`], [`Port`], and the
//! [`PortGroup`]/[`DagStruct`] traits that make composite state flow
//! through the DAG as port groups.

use std::fmt;
use std::marker::PhantomData;
use std::sync::Arc;

use crate::graph::arena::StateArena;
use crate::material::GpuBufferSlot;

/// Types that can flow through DAG ports.
///
/// Implemented for primitives (`f32`, `u32`, `i32`, `bool`, `usize`,
/// `String`, `()`), for `Vec<RectEntry>` / `Vec<TextObject>` (the render
/// outputs), and automatically for any struct deriving
/// [`DagStruct`](crate::DagStruct) (e.g. `Vec2`, `Rect`, or user state
/// structs).
pub trait PortValue: Clone + Default + 'static {}
impl PortValue for f32 {}
impl PortValue for u32 {}
impl PortValue for i32 {}
impl PortValue for bool {}
impl PortValue for usize {}
impl PortValue for String {}
// Vec2, Vec4, Vec2u, Vec2i, Rect — PortValue impl auto-generated by #[derive(DagStruct)]
impl PortValue for () {}
impl PortValue for Vec<crate::shader::RectEntry> {}
impl PortValue for Vec<crate::text::TextObject> {}
impl PortValue for Vec<u8> {}
impl PortValue for Option<Arc<GpuBufferSlot>> {}
impl PortValue for Option<Arc<wgpu::BindGroup>> {}

impl<I: crate::instance::GpuStruct + 'static> PortValue for crate::material::InstanceBuffer<I> {}

impl<M: crate::material::Material> PortValue for M {}

/// Unique identifier for a port within a graph.
/// Doubles as the index into `StateArena` slots.
///
/// Construct via [`PortId::new`] or obtain from [`Port::id`] /
/// [`PortGroup::port_ids`]. IDs are only valid for the arena they were
/// allocated from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct PortId(u64);

impl PortId {
    /// Wraps a raw slot index. Prefer obtaining ids from the arena
    /// ([`StateArena::alloc`]) or from existing ports.
    pub fn new(index: u64) -> Self {
        Self(index)
    }

    /// The underlying slot index.
    pub fn index(&self) -> u64 {
        self.0
    }
}

/// A typed handle to a value in the StateArena.
/// Multiple `Port<T>` handles can reference the same arena slot — "connection"
/// is just sharing the same PortId. Read/write goes through the arena
/// (zero-copy reads return references).
pub struct Port<T: PortValue> {
    id: PortId,
    _marker: PhantomData<T>,
}

// Manual Clone + Copy — Port<T> only contains PortId (u64) and PhantomData,
// both are always Copy/Clone regardless of T.
impl<T: PortValue> Clone for Port<T> {
    fn clone(&self) -> Self {
        *self
    }
}
impl<T: PortValue> Copy for Port<T> {}

impl<T: PortValue> Port<T> {
    /// Wraps an existing arena slot id. Prefer `arena.alloc` /
    /// `PortGroup::alloc_slots`, which allocate fresh slots.
    pub fn new(id: PortId) -> Self {
        Self {
            id,
            _marker: PhantomData,
        }
    }

    /// The id of the arena slot this handle reads/writes.
    pub fn id(&self) -> PortId {
        self.id
    }

    /// Re-point this handle at another slot. Only the graph builder
    /// re-wires handles; user code should treat the id as immutable.
    pub(crate) fn set_id(&mut self, id: PortId) {
        self.id = id;
    }
}

impl<T: PortValue> fmt::Debug for Port<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Port").field("id", &self.id).finish()
    }
}

/// Implemented by port group structs (manual or derive-generated).
/// Each group manages a set of leaf ports that can be connected as a unit.
///
/// # Hierarchical ports
///
/// A group maps to multiple leaf ports. For example, a `Vec2` port group
/// exposes two leaf `Port<f32>` ports (x, y). `connect_group` copies
/// PortIds positionally (leaf 0 → leaf 0, leaf 1 → leaf 1).
///
/// Every port — single or group — implements `PortGroup`. `Port<T>` is a
/// trivial 1-leaf group. Composite types get generated `{Name}Ports` structs.
pub trait PortGroup {
    /// Number of leaf ports in this group.
    fn leaf_count(&self) -> usize;

    /// Returns all leaf PortIds in this group, in order.
    fn port_ids(&self) -> Vec<PortId>;

    /// Extends `out` with all leaf PortIds (zero-allocation path).
    fn extend_ids(&self, out: &mut Vec<PortId>) {
        out.extend(self.port_ids());
    }

    /// Collects all leaf `PortId`s into a `Vec`.
    fn ids(&self) -> Vec<PortId> {
        let mut v = Vec::new();
        self.extend_ids(&mut v);
        v
    }

    /// Overwrites the leaf PortIds from the given slice (positional wiring).
    fn set_port_ids(&mut self, ids: &[PortId]);

    /// Allocate arena slots for all leaf ports (default-initialized).
    /// Used for standalone widgets (ports: None).
    fn alloc_slots(arena: &mut crate::graph::arena::StateArena) -> Self
    where
        Self: Sized;
}

// ── PortGroup impl for single Port<T> (trivial 1-leaf group) ────────────────

impl<T: PortValue> PortGroup for Port<T> {
    fn leaf_count(&self) -> usize {
        1
    }
    fn port_ids(&self) -> Vec<PortId> {
        vec![self.id]
    }
    fn extend_ids(&self, out: &mut Vec<PortId>) {
        out.push(self.id);
    }
    fn set_port_ids(&mut self, ids: &[PortId]) {
        assert_eq!(ids.len(), 1, "Port::set_port_ids: expected 1 id");
        self.id = ids[0];
    }
    fn alloc_slots(arena: &mut crate::graph::arena::StateArena) -> Self {
        Port::new(arena.alloc::<T>())
    }
}

// ── PortGroup impl for () — empty port group for source/sink nodes ─────────

impl PortGroup for () {
    fn leaf_count(&self) -> usize {
        0
    }
    fn port_ids(&self) -> Vec<PortId> {
        vec![]
    }
    fn extend_ids(&self, _out: &mut Vec<PortId>) {}
    fn set_port_ids(&mut self, _ids: &[PortId]) {}
    fn alloc_slots(_arena: &mut StateArena) -> Self {}
}

// ── Extend Port<T> with arena-based read/write convenience ─────────────────

impl<T: PortValue> Port<T> {
    /// Read the current value from the arena.
    pub fn read<'a>(&self, arena: &'a crate::graph::arena::StateArena) -> &'a T {
        arena.read(self.id)
    }

    /// Write a value into the arena (marks the slot dirty automatically).
    pub fn write(&self, arena: &mut crate::graph::arena::StateArena, value: T) {
        arena.write(self.id, value);
    }
}

// ── DagStruct trait (maps a value type to its port group) ──────────────────

/// Maps a value type to its port group type.
///
/// Every type that flows through DAG ports must implement `DagStruct`:
/// primitives get manual impls with `Ports = Port<T>`;
/// composite structs get generated impls via `#[derive(DagStruct)]`.
pub trait DagStruct: PortValue {
    /// The port group type holding this value's ports: `Port<T>` for
    /// primitives, `{Name}Ports` for `#[derive(DagStruct)]` structs.
    type Ports: PortGroup;

    /// Write this value into the port group via the arena.
    /// Used by the Widget derive to seed port buffers with initial values.
    fn write_ports(&self, arena: &mut crate::graph::arena::StateArena, ports: &Self::Ports);

    /// Reconstruct this value from the port group by reading arena slots.
    /// The inverse of [`write_ports`](Self::write_ports).
    fn read_ports(arena: &crate::graph::arena::StateArena, ports: &Self::Ports) -> Self;
}

// ── DagStruct impls for primitives ─────────────────────────────────────────

macro_rules! impl_dag_struct_scalar {
    ($t:ty) => {
        impl DagStruct for $t {
            type Ports = Port<$t>;
            fn write_ports(
                &self,
                arena: &mut crate::graph::arena::StateArena,
                ports: &Self::Ports,
            ) {
                ports.write(arena, self.clone());
            }
            fn read_ports(arena: &crate::graph::arena::StateArena, ports: &Self::Ports) -> Self {
                *ports.read(arena)
            }
        }
    };
}

impl_dag_struct_scalar!(f32);
impl_dag_struct_scalar!(u32);
impl_dag_struct_scalar!(i32);
impl_dag_struct_scalar!(bool);
impl_dag_struct_scalar!(usize);

impl DagStruct for String {
    type Ports = Port<String>;
    fn write_ports(&self, arena: &mut crate::graph::arena::StateArena, ports: &Self::Ports) {
        ports.write(arena, self.clone());
    }
    fn read_ports(arena: &crate::graph::arena::StateArena, ports: &Self::Ports) -> Self {
        ports.read(arena).clone()
    }
}

impl DagStruct for () {
    type Ports = Port<()>;
    fn write_ports(&self, _arena: &mut crate::graph::arena::StateArena, _ports: &Self::Ports) {}
    fn read_ports(_arena: &crate::graph::arena::StateArena, _ports: &Self::Ports) -> Self {}
}

impl DagStruct for Vec<crate::shader::RectEntry> {
    type Ports = Port<Vec<crate::shader::RectEntry>>;
    fn write_ports(&self, arena: &mut crate::graph::arena::StateArena, ports: &Self::Ports) {
        ports.write(arena, self.clone());
    }
    fn read_ports(arena: &crate::graph::arena::StateArena, ports: &Self::Ports) -> Self {
        ports.read(arena).clone()
    }
}

impl DagStruct for Vec<crate::text::TextObject> {
    type Ports = Port<Vec<crate::text::TextObject>>;
    fn write_ports(&self, arena: &mut crate::graph::arena::StateArena, ports: &Self::Ports) {
        ports.write(arena, self.clone());
    }
    fn read_ports(arena: &crate::graph::arena::StateArena, ports: &Self::Ports) -> Self {
        ports.read(arena).clone()
    }
}

// ── build_state_ports ────────────────────────────────────────────────────

/// Builds a port group for the given state struct: allocates arena slots
/// for every leaf port and writes initial values.
///
/// This is the standard way to turn a `#[derive(DagStruct)]` state struct
/// into live ports. The returned group shares its arena slots with
/// whatever is built afterwards — pass it (or clones of it) to DAG nodes
/// and to the `Widget` derive's `into_viewport_nodes(arena, Some(ports))`
/// so widget edits dirty the same slots the DAG reads.
///
/// ```ignore
/// let ports = build_state_ports(&state, app.arena_mut());
/// // ... app.graph_builder() ... app.finalize_graph() ...
/// let children = state.into_viewport_nodes(app.arena_mut(), Some(ports));
/// ```
pub fn build_state_ports<S: DagStruct>(state: &S, arena: &mut StateArena) -> S::Ports {
    let ports = S::Ports::alloc_slots(arena);
    S::write_ports(state, arena, &ports);
    ports
}

// ── port_ids free function ────────────────────────────────────────────────

/// Collects all leaf `PortId`s from any `PortGroup` into a `Vec`.
///
/// ```ignore
/// let inputs = port_ids(&(ports.operand1, ports.vec_a, ports.operand2));
/// b.add_node(eval, inputs, vec![]);
/// ```
pub fn port_ids(group: &impl PortGroup) -> Vec<PortId> {
    group.ids()
}

// ── PortGroup impls for tuples (compose heterogeneous port groups) ───────

impl<A: PortGroup, B: PortGroup> PortGroup for (A, B) {
    fn leaf_count(&self) -> usize {
        self.0.leaf_count() + self.1.leaf_count()
    }
    fn port_ids(&self) -> Vec<PortId> {
        self.ids()
    }
    fn extend_ids(&self, out: &mut Vec<PortId>) {
        self.0.extend_ids(out);
        self.1.extend_ids(out);
    }
    fn set_port_ids(&mut self, ids: &[PortId]) {
        let n0 = self.0.leaf_count();
        self.0.set_port_ids(&ids[..n0]);
        self.1.set_port_ids(&ids[n0..]);
    }
    fn alloc_slots(_arena: &mut StateArena) -> Self {
        unreachable!("tuple PortGroup: use build_state_ports or alloc_slots on individual ports")
    }
}

impl<A: PortGroup, B: PortGroup, C: PortGroup> PortGroup for (A, B, C) {
    fn leaf_count(&self) -> usize {
        self.0.leaf_count() + self.1.leaf_count() + self.2.leaf_count()
    }
    fn port_ids(&self) -> Vec<PortId> {
        self.ids()
    }
    fn extend_ids(&self, out: &mut Vec<PortId>) {
        self.0.extend_ids(out);
        self.1.extend_ids(out);
        self.2.extend_ids(out);
    }
    fn set_port_ids(&mut self, ids: &[PortId]) {
        let n0 = self.0.leaf_count();
        let n1 = n0 + self.1.leaf_count();
        self.0.set_port_ids(&ids[..n0]);
        self.1.set_port_ids(&ids[n0..n1]);
        self.2.set_port_ids(&ids[n1..]);
    }
    fn alloc_slots(_arena: &mut StateArena) -> Self {
        unreachable!("tuple PortGroup: use build_state_ports or alloc_slots on individual ports")
    }
}

impl<A: PortGroup, B: PortGroup, C: PortGroup, D: PortGroup> PortGroup for (A, B, C, D) {
    fn leaf_count(&self) -> usize {
        self.0.leaf_count() + self.1.leaf_count() + self.2.leaf_count() + self.3.leaf_count()
    }
    fn port_ids(&self) -> Vec<PortId> {
        self.ids()
    }
    fn extend_ids(&self, out: &mut Vec<PortId>) {
        self.0.extend_ids(out);
        self.1.extend_ids(out);
        self.2.extend_ids(out);
        self.3.extend_ids(out);
    }
    fn set_port_ids(&mut self, ids: &[PortId]) {
        let n0 = self.0.leaf_count();
        let n1 = n0 + self.1.leaf_count();
        let n2 = n1 + self.2.leaf_count();
        self.0.set_port_ids(&ids[..n0]);
        self.1.set_port_ids(&ids[n0..n1]);
        self.2.set_port_ids(&ids[n1..n2]);
        self.3.set_port_ids(&ids[n2..]);
    }
    fn alloc_slots(_arena: &mut StateArena) -> Self {
        unreachable!("tuple PortGroup: use build_state_ports or alloc_slots on individual ports")
    }
}
